#!/bin/bash

# Global const
DEFAULT_BOOT_MOUNT_POINT="./src_boot/"
DEFAULT_ROOT_MOUNT_POINT="./src_root/"
BOOT_FS_TYPE="vfat"
ROOT_FS_TYPE="ext4"

function help_message() {
    prog=$1
    cat <<  EOF
Usage: ${prog}
    -h, --help                       
        Print help message.

    -dev, --device=[device]     
        Required. 
        Device to be dumped from, example "/dev/mmcblk0".

    -bdev, --boot-device=[device] 
        Boot device, must be vfat type.
        If not specified, '{name-of-dev}'+"p1" will be used, exmple "/dev/mmcblk0p1".
        If not mounted, it will be mounted on ${DEFAULT_BOOT_MOUNT_POINT}.

    -rdev, --root-device=[device]
        Root device, must be ext4 type.
        If not specified, '{name-of-dev}'+"p2" will be used, example "/dev/mmcblk0p2"
        If not mounted, it will be mounted on ${DEFAULT_ROOT_MOUNT_POINT}.
EOF
}

function echo_succ() {
    msg=$1
    echo -e "\033[;32m ${msg} \033[0m"
}
function echo_succ_n() {
    msg=$1
    echo -ne "\033[;32m ${msg} \033[0m"
}

function echo_error() {
    msg=$1
    echo -e "\033[;31m ${msg} \033[0m"
}

function echo_error_n() {
    msg=$1
    echo -ne "\033[;31m ${msg} \033[0m"
}

function check_bin() {
    bin=$1

    echo -n  "checking ${bin} ... "
    loc=`which ${bin}` || { echo_error "not found"; return 1; }
    echo_succ "${loc}"
}

function check_dev() {
    dev=$1

    echo -n "checking device ${dev} ... "
    sudo ${FDISK} -l ${dev} > /dev/null 2>&1 || { echo_error "doesn't exists"; return 1; }
    echo_succ "ok"
}

function check_mount_point() {
    dev=$1
    if_mounted=True
    mount_point=""
    fs_type=""
    
    sudo ${MOUNT} -l | grep "${dev}" > /dev/null 2>&1 || if_mounted=False
    #if_mounted=False
    if [ ${if_mounted} == False ]
    then
        echo "${if_mounted}"
        return
    fi

    mount_point=`sudo ${MOUNT} -l | grep ${dev} | awk '{print $3}'`
    fs_type=`sudo ${MOUNT} -l | grep ${dev} | awk '{print $5}'`
    echo "${if_mounted} ${mount_point} ${fs_type}"
}

## Parse arguments
if_help=false
device=""
boot_device=""
root_device=""
for opt
do
    case ${opt} in
        -*=*) value=$(echo "$opt"|sed -e 's/[-_a-zA-Z0-9]*=//') ;;
           *) value=""                                          ;;
    esac

    case ${opt} in
        -h|--help)                  if_help=true                                  ;;
        -dev=*|--device=*)          device=${value}                               ;;
        -bdev=*|--boot-device=*)    boot_device=${value}                          ;;
        -rdev=*|--root-device=*)    root_device=${value}                          ;;
        *) echo "invalid argument $opt"
           exit 1
           ;;
    esac
done

[ ${if_help} == true ] && help_message $0 && exit 0
[ "${device}" == "" ] && echo "-dev|--device is required" && exit 1
[ "${boot_device}" == "" ] && boot_device="${device}p1" && echo "Boot device is not specified, use \"${boot_device}\""
[ "${root_device}" == "" ] && root_device="${device}p2" && echo "Root device is not specified, use \"${root_device}\""

echo ""
echo "[Check tools]"
check_bin "pv"        || exit 1
check_bin "fdisk"     || exit 1
check_bin "mount"     || exit 1
check_bin "parted"    || exit 1
check_bin "kpartx"    || exit 1
check_bin "mkfs.vfat" || exit 1
check_bin "mkfs.ext4" || exit 1
check_bin "losetup"   || exit 1
check_bin "blkid"     || exit 1

FDISK=$(which fdisk)
MOUNT=$(which mount)
PARTED=$(which parted)
KPARTX=$(which kpartx)
MKFS_VFAT=$(which mkfs.vfat)
MKFS_EXT4=$(which mkfs.ext4)
LOSETUP=$(which losetup)
BLKID=$(which blkid)

echo ""
echo "[Check device]"
check_dev ${device}      || exit 1
check_dev ${boot_device} || exit 1
check_dev ${root_device} || exit 1

echo ""
echo "[Check mount point]"
if_boot_mounted=True
if_root_mounted=True
boot_mount_point=""
boot_fs_type=""
root_mount_point=""
root_fs_type=""

read if_boot_mounted boot_mount_point boot_fs_type < <(check_mount_point "${boot_device}")
read if_root_mounted root_mount_point root_fs_type < <(check_mount_point "${root_device}")

if [ ${if_boot_mounted} == True ] 
then
    echo -n "${boot_device} mounted on ${boot_mount_point}, ${boot_fs_type} ..."
    [ ${boot_fs_type} != ${BOOT_FS_TYPE} ] && echo_error_n "Error: " && echo "Boot fs type must be ${BOOT_FS_TYPE}" && exit 1
    echo_succ "ok"
fi

if [ ${if_root_mounted} == True ] 
then
    echo -n "${root_device} mounted on ${root_mount_point}, ${root_fs_type} ..."
    [ ${root_fs_type} != ${ROOT_FS_TYPE} ] && echo_error_n "Error: " && echo "Root fs type must be ${ROOT_FS_TYPE}" && exit 1
    echo_succ "ok"
fi

echo ""
echo "[Mount device if necessary]"
if [ ${if_boot_mounted} == False ]  
then
    # TODO
    echo "Mounting ${boot_device} to ${DEFAULT_BOOT_MOUNT_POINT}"   
    #boot_mount_point=${DEFAULT_BOOT_MOUNT_POINT}
    #boot_fs_type=${BOOT_FS_TYPE}
fi

if [ ${if_root_mounted} == False ]  
then
    # TODO
    echo "Mounting ${root_device} to ${DEFAULT_ROOT_MOUNT_POINT}"   
    #root_mount_point=${DEFAULT_ROOT_MOUNT_POINT}
    #root_fs_type=${ROOT_FS_TYPE}
fi

function get_fs_size_MB() {
    mp=$1
    sudo df ${mp} | sed 1d | awk '{print int($2/1024) }'
}

function get_fs_used_MB() {
    mp=$1
    sudo df ${mp} | sed 1d | awk '{print int($3/1024) }'
}

echo ""
echo "[Create img file]"
boot_fs_size_MB=`get_fs_size_MB "${boot_mount_point}"`
root_fs_used_MB=`get_fs_used_MB "${root_mount_point}"`
echo "Boot fs size: ${boot_fs_size_MB}MB"
echo "Root fs size: ${root_fs_used_MB}MB"
img_file_size_MB=`echo "${boot_fs_size_MB}+${root_fs_used_MB}+500" | bc ` # 500MB larger
echo "New img file size: ${img_file_size_MB}MB"
img_file="pi-`date +20%y%m%d%H%M`.img"
#img_file="pi-test.img" # HACKED
echo "Creating ${img_file}..."
sudo dd bs=1M count=${img_file_size_MB} if=/dev/zero | pv -s ${img_file_size_MB}M | sudo dd bs=1M of=./${img_file}
ls -l ./${img_file} > /dev/null 2>&1 || { echo_error_n "Error:"; echo "${img_file} not found"; exit 1; }
echo_succ "..........................ok"

echo ""
echo "[Make partitions]"
boot_start_sector=`sudo ${FDISK} -l ${device} | grep "${boot_device}" | awk '{print $2}'`
boot_end_sector=`sudo ${FDISK} -l ${device} | grep "${boot_device}" | awk '{print $3}'`
root_start_sector=`sudo ${FDISK} -l ${device} | grep "${root_device}" | awk '{print $2}'`
echo "${boot_device} sectors: ${boot_start_sector}s ${boot_end_sector}s"
echo "${root_device} sectors: ${root_start_sector}s -1"

sudo ${PARTED} ${img_file} --script mklabel msdos
sudo ${PARTED} ${img_file} --script mkpart primary fat32 ${boot_start_sector}s ${boot_end_sector}s
sudo ${PARTED} ${img_file} --script mkpart primary ext4 ${root_start_sector}s 
